### ISSUE TITLE
[FE] Create button component

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-wiki#12]

**Comment by Lahali** [comment]
@vicenlu En el botón, no encuentro definidas las variantes de hover y active del botón secundario (el amarillo). Te dejo screenshot del figma 

![Image](https://user-images.githubusercontent.com/101599560/226881380-5f85aeb0-d355-4c31-89f4-ce4ef6094315.png)

**Comment by Lahali** [comment]
Siguiendo con el tema de los colores, los botones active tienen 3 fondos diferentes, entiendo que el outline debería ser diferente, pero no estoy segura si en Icon Text no deberían de ser iguales. Me baso en que en default y hover el color es igual. @vicenlu
