### ISSUE TITLE
1.1 Login

### ISSUE THREAD

**Issue by vicenlu** [IT-Academy-BCN/ita-wiki#2]
As a user, I want to be able to log in to the web platform using my identification document and password, in order to access my account. 

Use cases:

- If the data is correct, the user should be redirected to the platform's home page.

- If any data is incorrect, the user should be informed that the entered data is incorrect.

**Comment by kevinmamaqi** [comment]
Please, specify error messages for this:

> If any data is incorrect, the user should be informed that the entered data is incorrect

and add link to the design (specific of this story)

**Comment by kevinmamaqi** [comment]
Update design with:

- DNI/NIE
- Ask Esther, how we would preload existing data.

**Comment by Spanioulis** [comment]
Hi @vicenlu, we need specifications for when a user is already logged in. Thanks!

**Comment by vicenlu** [comment]
Use case:

- User ser logs in
- User access the web.
- User enters the login url, he must be redirected to home, validating his cookie or session token.

If the user wants to access the login once logged in, the user must log out.
