### ISSUE TITLE
[BE] regorganize VOTE endpoint put/get

### ISSUE THREAD

**Issue by oriolsastre** [IT-Academy-BCN/ita-wiki#233]
- [x] Make the ``api/v1/vote`` endpoint handle the PUT method.
- ResourceId and vote info should be send in the body.
- Vote info should be something readable like "up", "down", "cancel", and translated as 1,-1,0 in the controller.

- [ ] Also, resource getters should include voteCount information.

- voteCount schema should be something like:
``` js
voteCount: {
  upvote: Number,
  downvote: Number,
  total: Number
}
```

- [x] Exclude vote endpoint from the resource tag on the openAPI.

**Comment by kevinmamaqi** [comment]
The put should return 204 only, for now at least
