### ISSUE TITLE
[FE] Create a default All topics selector, preselected on the filters

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-wiki#343]
<img width="230" alt="Screenshot 2023-07-03 at 10 06 04" src="https://github.com/IT-Academy-BCN/ita-wiki/assets/972664/9a96a02d-7d65-46bb-a723-d04f8cf1ddb7">

**Comment by NataliaR-BCN** [comment]
Hecho por otra vía
