### ISSUE TITLE
[FE] Create filters context

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-wiki#344]
Define:
- Shape of the context
- Functions of the context
- Default values

Consider introducing all the context in a custom hook to have a more declarative api, for instance:
`const { useUpdateFilters } = FiltersContext();`
`const { useGetFilters } = FiltersContext();`

**Comment by mitild** [comment]
At the app’s first render, I would fetch all topics, types, and statuses. 
For that, I would: add a “getTypes” to the “fetchers” file. 

Then I would go for something like this: 

`type FilterContextType = {
  types: string[]
  topics: string[]
  status: string[]
  setTypes: (types: string[]) => void
  setTopics: (topics: string[]) => void
  setStatus: (status: string[]) => void
}

const FiltersContext = createContext<FilterContextType | undefined>(undefined)

const defaultFilters = {
  types: [getTypes()],
  topics: [getTopics()],
  status: ['NOT_SEEN', 'SEEN'],
}

const FiltersProvider: FC = ({ children }) => {
  const [filters, setFilters] = useState(defaultFilters)

  const setTypes = (types: string[]) => {
    setFilters((prevFilters) => ({ ...prevFilters, types }))
  }

  const setTopics = (topics: string[]) => {
    setFilters((prevFilters) => ({ ...prevFilters, topics }))
  }

  const setStatus = (status: string[]) => {
    setFilters((prevFilters) => ({ ...prevFilters, status }))
  }

  return (
    <FiltersContext.Provider value={{ ...filters, setTypes, setTopics, setStatus }}>
      {children}
    </FiltersContext.Provider>
  )
}

const useUpdateFilters = () => {
  const context = useContext(FiltersContext)
  if (!context) {
    throw new Error('useUpdateFilters must be used within a FiltersProvider')
  }
  return context
}

const useGetFilters = () => {
  const context = useContext(FiltersContext)
  if (!context) {
    throw new Error('useGetFilters must be used within a FiltersProvider')
  }
  return {
    types: context.types,
    topics: context.topics,
    status: context.status,
  }
}

export { FiltersProvider, useUpdateFilters, useGetFilters }`

Lastly, I would make use of the two hooks in every component that uses it.

**Comment by mitild** [comment]
First, fetch resources based on the category using getCategories, and save it in a state within the context. Utilize useMemo to ensure it only changes when the category changes. Then, retrieve the list of topics for that category, the list of types, and the status. Afterward, select the 'todos' topic by default (no changes needed as all resources have been fetched). When a new topic is selected, filter the saved resources using useMemo. The results with the filtered resources will be accessible through the useGetUpdatedFilters hook (along with setters), and the array with all resources of the default category will be passed through another hook called useGetFilters.
