### ISSUE TITLE
[BE] Modify registerController so duplicates are automatically handled by errorMiddleware

### ISSUE THREAD

**Issue by alex0rpi** [IT-Academy-BCN/ita-wiki#448]
Modify registerController:
- rename to register plain, without 'Controller' which is redundant given the folder it belongs to.
- the duplicate email or DNI should be detected by Prisma and handled by errorMiddleware, just like it is done with userPatch (see /controllers/users/patch).

**Comment by xpan1c** [comment]
Implement a system to detect which error Prisma throws and then produce a customized error message.
