### ISSUE TITLE
[BE][BUG] Fix GET Favorite Resources by user endpoint 

### ISSUE THREAD

**Issue by NataliaR-BCN** [IT-Academy-BCN/ita-wiki#487]
/api/v1/resources/favorites
Avoid response with nested resource: 
![getFavResourcesvsSwagger2](https://github.com/IT-Academy-BCN/ita-wiki/assets/92027716/9cd28905-ebed-4c24-96e6-aad40caee24e)
Filter by category (slug) is optional

**Comment by xpan1c** [comment]
add voteCount
