### ISSUE TITLE
[BE] endpoint PUT "/api/v1/favorites" accepts an entire "Resource" on the request

### ISSUE THREAD

**Issue by SergiFont** [IT-Academy-BCN/ita-wiki#550]
It should only accept a CUID on the request, not an entire Resource.

**Comment by alejandroN99** [comment]
already accepts a CUID

**Comment by xpan1c** [comment]
https://github.com/IT-Academy-BCN/ita-wiki/blob/83cd088c680c0ca23b898d8c7e049d05b3484bf4/back/src/schemas/favorites/favoritePutSchema.ts#L3-L14
