### ISSUE TITLE
[BE] Filter by seen/not_seen not working 

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-wiki#585]

**Comment by xpan1c** [comment]
The endpoint is functioning as expected in swagger. However, in the 'seen' request, it's blending the 'not seen' with the 'seen'."
![image](https://github.com/IT-Academy-BCN/ita-wiki/assets/113645971/5dc94b3c-0d4f-4f35-8744-d034417503ee)
