### ISSUE TITLE
[BE] [BUG] Add topics to getFavorites response

### ISSUE THREAD

**Issue by NataliaR-BCN** [IT-Academy-BCN/ita-wiki#596]
The favorites resources returned are incomplete: they have to include the same data as other resources, because a favorite resource is just a regular resource with isFavorite: true.
Screenshot: favorite vs resource:
![favsVsres](https://github.com/IT-Academy-BCN/ita-wiki/assets/92027716/feb6a4a2-9dad-45fe-8c58-e637ca579dab)

**Comment by alex0rpi** [comment]
You want the API to return as much information as the GET endpoint right?
Ok but the isFavorite property would be redundant, since they all com from the Favorites list.

**Comment by NataliaR-BCN** [comment]
> You want the API to return as much information as the GET endpoint right? 
 + Yes, as GET resources! 
Ok but the isFavorite property would be redundant, since they all com from the Favorites list.
 + Yes, maybe. Is there any problem with that? 
 I need this property to fill the favorite icon in the Resource Card. 
 Favorites are just resources with isFavorite: true.
    
![2023-10-31 (1)](https://github.com/IT-Academy-BCN/ita-wiki/assets/92027716/59dfa8a0-32ef-4323-8d6b-2e67b289e0b3)

**Comment by alex0rpi** [comment]
ok but if it comes from favorites the heart should be filled already by default right? 
Your picture comes from the main list of resources which if I am not mistaken uses the GET request "http://localhost:5173/api/v1/resources" endpoint which contains the isFavorite property.

**Comment by NataliaR-BCN** [comment]
The heart icon is filled based on isFavorite value (true: filled), that's why I need this property updated.
The pictures comes from the main list of resources, right, I used to show you what I mean.
