### ISSUE TITLE
[BE] [BUG] Check why userVote is 0 at resources GET endpoints

### ISSUE THREAD

**Issue by NataliaR-BCN** [IT-Academy-BCN/ita-wiki#597]
Endpoint GET /api/v1/resources/me has to be updated:
- Avoid nested data
- Allow optional filtering by slug 
- Make sure it updates correctly when changes the info in isFavorite and Votes

**Comment by alex0rpi** [comment]
Hello,
* Avoid nested data
>>TBC so, you mean avoid topic:[ topic: {...}, topic: {...}, ... ]
* Allow optional filtering by slug
>>it already allows a slug query param ✅
* Make sure it updates correctly when changes the info in isFavorite and Votes 
>>The controller only returns resources created by a particular user, regardless whether their're favorite or not or their votes.

**Comment by NataliaR-BCN** [comment]
> Hello,
> 
> * Avoid nested data
> 
> > > TBC so, you mean avoid topic:[ topic: {...}, topic: {...}, ... ]
> No, I mean resources: [ { resource1}, { resource2},...] 
Please mantain the inner structure of resources
> * Allow optional filtering by slug
> 
> > > it already allows a slug query param ✅
Ok!
> 
> * Make sure it updates correctly when changes the info in isFavorite and Votes
> 
> > > The controller only returns resources created by a particular user, regardless whether their're favorite or not or their votes.
Yes, but... is isFavorite and userVote updated when this data changes?

**Comment by alex0rpi** [comment]
> Hello,
> 
> * Avoid nested data
> 
> > > TBC so, you mean avoid topic:[ topic: {...}, topic: {...}, ... ]
> > > No, I mean resources: [ { resource1}, { resource2},...]
>>>> Currently it returns:
```JSON
{ "resources" : [ {  }, {  }, {   } ] }
```
>>>>So eliminate the first "resources" and have just an array of objects right?
> > > Please mantain the inner structure of resources
>>>>OK
> 
> * Allow optional filtering by slug
> 
> > > it already allows a slug query param ✅
> > > Ok!
> 
> * Make sure it updates correctly when changes the info in isFavorite and Votes
> 
> > > The controller only returns resources created by a particular user, regardless whether their're favorite or not or their votes.
> > > Yes, but... are isFavorite and userVote updated when their data changes?
>>>> YES, each time someone hits the heart or a vote sign, the put requests modify the favorites and vote tables respectively and we fetch the isFavorite and voteCount info from those tables.
