### ISSUE TITLE
[FE][BE][BUG] Patch user status

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-wiki#614]
<img width="1688" alt="Screenshot 2023-11-09 at 09 28 23" src="https://github.com/IT-Academy-BCN/ita-wiki/assets/972664/101d8b80-9645-48ad-b0ad-96e08b1b40d1">

**Comment by xpan1c** [comment]
It seems that the Prisma validation error is triggered when sending the PATCH request payload to modify a user's status.
```json
{
    "id": "clowqp1ze0006u17ka7jwgp24",
    "email": "registered@registered.com",
    "dni": "23456789B",
    "name": "Django Unchained",
    "specialization": "clowqp1so0000u17ksbqud1h9",
    "status": "ACTIVE",
    "role": "REGISTERED",
    "createdAt": "2023-11-13T10:06:18.698Z",
    "updatedAt": "2023-11-13T10:06:18.698Z"
  } 
```
https://www.prisma.io/docs/reference/api-reference/error-reference#prismaclientvalidationerror
