### ISSUE TITLE
[BUG][FIX][FE] Same height columns

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-wiki#641]
![issue1](https://github.com/IT-Academy-BCN/ita-wiki/assets/972664/99105316-f61c-4ff8-bc9b-7995805a89ff)

**Comment by NataliaR-BCN** [comment]
Sure?? Look at Figma desing!
![2023-11-20 (1)](https://github.com/IT-Academy-BCN/ita-wiki/assets/92027716/3e565f5b-7757-4d45-ae5b-e338fd75befb)

**Comment by kevinmamaqi** [comment]
@vicenlu por favor confirma

**Comment by vicenlu** [comment]
Bien visto @NataliaR-BCN. Los arreglos visuales para la demo tienen preferencia respecto al diseño de Figma, ya que por limitaciones de tiempo es complicado actualizarlo con todas las novedades.
Para que no haya confusión, he actualizado el figma para recoger este cambio:


<img width="908" alt="Captura de pantalla 2023-11-23 a las 15 32 11" src="https://github.com/IT-Academy-BCN/ita-wiki/assets/24873762/0a5eacf3-6c2a-458d-ad99-613dafe41ddb">

**Comment by NataliaR-BCN** [comment]
Perfecto, @vicenlu, mil gracias por confirmar y por la guía visual!
