### ISSUE TITLE
[FE] Comenzar con el sso_front

### ISSUE THREAD

**Issue by kevinmamaqi** [IT-Academy-BCN/ita-wiki#799]
- [ ] Preparar carpeta
- [ ] CI principales

INITIAL STEPS (refer to discussion #803 for more information)
 - [x] #809
 - [x] #810
 - [ ] #811
 - [ ] #812

**Comment by marmorrei** [comment]
- [ ] Create the initial structure of `sso_front`, empty.
- [ ] Configure `package.json`, `tsconfig`, `dockerfile`, `eslint`, `prettier`, and `vite.config`. (Here, we need to set up a proxy to connect with SSO.
- [ ] Configure tests in the `src` folder.
- [ ] Implement coverage and integrate with SonarCloud.
